apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - name: internal
    port: 9092
  - name: external
    port: 9093
  selector:
    app: kafka
  clusterIP: None
