apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-reader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-reader
  template:
    metadata:
      labels:
        app: temperature-reader
    spec:
      containers:
      - name: temperature-reader
        image: temperature-reader:v1
        imagePullPolicy: Never
        env:
        - name: KAFKA_TOPIC
          value: temperature
        - name: KAFKA_BROKERS
          value: kafka-service:9092
        - name: CONSUMER_GROUP
          value: temperature-reader
